# inherit_from: rubocop-todo.yml
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - tmp/**/*
    - log/**/*
    - vendor/**/*
    - db/schema.rb
    - public/packs
    - public/packs-test
    - public/uploads
    - node_modules/**/*
    - bin/bundle
    - bin/rubocop
    - bin/update
    - bin/setup
    - bin/webpack
    - bin/webpack-dev-server
    - bin/spring
    - lib/tasks/*

Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/routes.rb
    - spec/**/*
    - Guardfile

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['\A#']
  Exclude:
    - db/migrate/*
    - config/initializers/devise.rb

Metrics/MethodLength:
  Exclude:
    - app/controllers/users/registrations_controller.rb
    - db/migrate/*

Rails:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/FilePath:
  Exclude:
    - config/environments/development.rb

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/users/*

RSpec/ContextWording:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Exclude:
    - bin/yarn

Style/StringLiterals:
  Exclude:
    - Gemfile
    - Guardfile
    - bin/yarn
    - config/environments/production.rb
    - config/puma.rb
    - config/application.rb
    - spec/rails_helper.rb

Style/StderrPuts:
  Exclude:
    - bin/yarn

Style/BlockComments:
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/RegexpLiteral:
  Exclude:
    - Guardfile

Style/SymbolArray:
  Exclude:
    - Gemfile

Layout/EmptyLines:
  Exclude:
    - Gemfile
    - bin/setup

# Lint/SplatKeywordArguments:
#   Exclude:
#     - config/initializers/shrine.rb
