# inherit_from: rubocop-todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - public/packs
    - public/packs-test
    - node_modules/**/*
    - bin/update
    - bin/setup
    - bin/webpack
    - bin/webpack-dev-server
    - bin/spring
    - lib/tasks/*
    - config/initializers/materialize.rb

Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_materialize.rb
    - spec/**/*

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['\A#']
  Exclude:
    - db/migrate/*
    - config/initializers/devise.rb

Metrics/MethodLength:
  Exclude:
    - app/controllers/users/registrations_controller.rb
    - db/migrate/*

Rails:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/FilePath:
  Exclude:
    - config/environments/development.rb

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/users/*

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Exclude:
    - bin/yarn

Style/StringLiterals:
  Exclude:
    - Gemfile
    - bin/yarn
    - config/environments/production.rb
    - config/initializers/simple_form_materialize.rb
    - config/puma.rb
    - config/application.rb
    - spec/rails_helper.rb

Style/StderrPuts:
  Exclude:
    - bin/yarn

Style/BlockComments:
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/SymbolArray:
  Exclude:
    - Gemfile

Layout/AlignHash:
  Exclude:
    - config/initializers/simple_form.rb

Layout/EmptyLines:
  Exclude:
    - Gemfile
    - bin/setup

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_materialize.rb
