version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: app_development
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  rails: &app_base
    build: .
    image: ofl/entry_point_2018:0.1
    ports:
      - '3000:3000'
      - '8080:8080'
    volumes:
      - .:/usr/src/entry_point_2018
      - bundle_cache:/bundle
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: app_development
    command: bundle exec foreman start -f Procfile.dev
  spring:
    <<: *app_base
    stdin_open: true
    tty: true
    command: spring server
    ports: []
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: app_development
      SPRING_SOCKET: /tmp/spring/spring.sock
    volumes:
      - .:${PWD}
      - spring:/tmp/spring
volumes:
  postgresql-data:
    driver: local
  bundle_cache:
  spring:
