version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: app_development
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  rails:
    build: .
    image: ofl/entry_point_2018:0.1
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/entry_point_2018
      - bundle_cache:/usr/local/bundle
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: app_development
volumes:
  postgresql-data:
    driver: local
  bundle_cache:
