version: '3'
services:
  rails:
    env_file: .env
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    image: ${DEVELOPER_NAME}/${PROJECT_NAME}_rails:${APP_VERSION}
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
      - ~/.ash_history:/root/.ash_history
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: app_development
    command: bundle exec foreman start -f Procfile.dev

  postgres:
    env_file: .env
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: app_development
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

  yarn:
    build:
      context: .
      dockerfile: ./docker/yarn/Dockerfile
    image: ${DEVELOPER_NAME}/${PROJECT_NAME}_yarn:${APP_VERSION}
    # command: yarn watch
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  postgresql-data:
    driver: local
  bundle-volume:
  node_modules:
