apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status:
  phase: Pending
