bundle_cache_key: &bundle_cache_key
  bundle-{{ checksum "Gemfile.lock" }}

version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
      environment:
        RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: rubocop
          command: docker-compose run --rm rails bundle exec rubocop --config .rubocop.yml
      - run:
          name: "before_test: setup db"
          command: docker-compose run --rm rails rails db:create db:migrate
      - run:
          name: "before_test: install javascript dependencies"
          command: docker-compose run --rm rails yarn
      - run:
          name: rspec
          command: >
            docker-compose run
            -e CONFIRMATION_EXPIRED=$CONFIRMATION_EXPIRED
            -e CONFIRMATION_MAIL_EXPIRED=$CONFIRMATION_MAIL_EXPIRED
            -e TWITTER_API_KEY=$TWITTER_API_KEY
            -e TWITTER_API_SECRET=$TWITTER_API_SECRET
            -e TWITTER_TEST_ACCESS_SECRET=$TWITTER_TEST_ACCESS_SECRET
            -e TWITTER_TEST_ACCESS_TOKEN=$TWITTER_TEST_ACCESS_TOKEN
            -e TWITTER_TEST_UID=$TWITTER_TEST_UID
            -e FACEBOOK_APP_ID=$FACEBOOK_APP_ID
            -e FACEBOOK_APP_SECRET=$FACEBOOK_APP_SECRET
            -e FACEBOOK_TEST_UID=$FACEBOOK_TEST_UID
            -e FACEBOOK_TEST_ACCESS_TOKEN=$FACEBOOK_TEST_ACCESS_TOKEN
            --rm rails bundle exec rake spec SPEC_OPTS="--color --fail-fast"
      - run:
          name: docker-compose down
          command: docker-compose down

  auto_bundle_update:
    machine:
      image: circleci/classic:edge
      environment:
        RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: sleep for waiting launch db
          command: sleep 1

      - restore_cache:
          key: *bundle_cache_key

      - run:
          name: circleci-bundle-update-pr
          command: |
            docker-compose run --rm gem update bundler -N
            docker-compose run --rm gem install circleci-bundle-update-pr -N
            docker-compose run -e GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN --rm circleci-bundle-update-pr $GITHUB_USER_NAME $GITHUB_USER_EMAIL
      - run:
          name: docker-compose down
          command: docker-compose down

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
  auto_bundle_update:
    triggers:
      - schedule:
          cron: "00 1 * * 1" # 毎週月曜日
          filters:
            branches:
              only:
                - master
    jobs:
      - auto_bundle_update
