version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
      environment:
        RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: rubocop
          command: docker-compose run --rm app bundle exec rubocop
      - run:
          name: "before_test: setup db"
          command: docker-compose run --rm app rails db:create db:migrate
      - run:
          name: rspec
          command: docker-compose run --rm app bundle exec rake spec SPEC_OPTS="--color --fail-fast"
      - run:
          name: docker-compose down
          command: docker-compose down
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
