version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
      environment:
        RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: rubocop
          command: docker-compose run --rm rails bundle exec rubocop
      - run:
          name: "before_test: setup db"
          command: docker-compose run --rm rails rails db:create db:migrate
      - run:
          name: rspec
          command: >
            docker-compose run
            -e CONFIRMATION_EXPIRED=$CONFIRMATION_EXPIRED
            -e CONFIRMATION_MAIL_EXPIRED=$CONFIRMATION_MAIL_EXPIRED
            -e TWITTER_API_KEY=$TWITTER_API_KEY
            -e TWITTER_API_SECRET=$TWITTER_API_SECRET
            -e TWITTER_TEST_ACCESS_SECRET=$TWITTER_TEST_ACCESS_SECRET
            -e TWITTER_TEST_ACCESS_TOKEN=$TWITTER_TEST_ACCESS_TOKEN
            -e TWITTER_TEST_UID=$TWITTER_TEST_UID
            -e FACEBOOK_APP_ID=$FACEBOOK_APP_ID
            -e FACEBOOK_APP_SECRET=$FACEBOOK_APP_SECRET
            -e FACEBOOK_TEST_UID=$FACEBOOK_TEST_UID
            -e FACEBOOK_TEST_ACCESS_TOKEN=$FACEBOOK_TEST_ACCESS_TOKEN
            --rm rails bundle exec rake spec SPEC_OPTS="--color --fail-fast"
      - run:
          name: docker-compose down
          command: docker-compose down
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
