default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: postgres
  port: 5432

production:
  <<: *default
  database: app_production

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
