twitter:
  api_key: <%= ENV["TWITTER_API_KEY"] %>
  api_secret: <%= ENV["TWITTER_API_SECRET"] %>
  test_uid: <%= ENV["TWITTER_TEST_UID"] %>
  test_access_token: <%= ENV["TWITTER_TEST_ACCESS_TOKEN"] %>
  test_access_secret: <%= ENV["TWITTER_TEST_ACCESS_SECRET"] %>

facebook:
  app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  app_secret: <%= ENV["FACEBOOK_APP_ID"] %>
  test_uid: <%= ENV["FACEBOOK_TEST_UID"] %>
  test_access_token: <%= ENV["FACEBOOK_TEST_ACCESS_TOKEN"] %>
  
confirmation:
  expired: 60 # minutes
  mail_expired: 60 # minutes
