domain: example.com
confirmation:
  expired: 60 # minutes
  mail_expired: 60 # minutes
models:
  user:
    username:
      minlength: 3
      maxlength: 15
  point:
    expiration_interval: 90 # days
uploaders:
  default: &default
    max_size: 2 # MB
    allowed_mime_types:
      - image/png
      - image/jpeg
      - image/gif
  avatar:
    <<: *default
